Repository graphprotocol/graph-ts, pull requests merged in 2018-11, with the labels that each got.

#15 Add `global/global.ts` exporting `allocate_memory`
  global/global.ts
Labels: pending review

#18 README: Update usage example to use a generated entity type
  README.md
Labels: area/ts, documentation, pending review

#20 Add +, -, *, / and % support for BigInt
  index.ts
Labels: area/ts, developer experience, new feature, pending review

#19 Add properties to the EtheremTransaction and EthereumEvent classes
  index.ts
Labels: pending review

#21 Accept both INT and UINT in `EthereumValue.toI32`
  index.ts
Labels: bug, pending review

#25 docs update done
  README.md
Labels: pending review
