Repository graphprotocol/graph-ts, pull requests merged in 2018-10, with the labels that each got.

#3 index.ts: Use `i32` instead of `u32` in value conversions
  index.ts
Labels: pending review

#4 index.ts: Fix EthereumValue numeric conversions
  index.ts
Labels: pending review

#2 Add Ethereum block and transaction data to events
  index.ts
Labels: enhancement, new feature, pending review

#6 Fix bytesToString signature
  index.ts
Labels: bug, pending review
